### ISSUE TITLE
Student Enrollments spec: a few questions

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#56] opened 2019-08-06 15:01 UTC
1) Should we allow date creation customization?

![Schermata 2019-08-06 alle 16 29 36](https://user-images.githubusercontent.com/7689242/62548732-90ae6000-b867-11e9-995d-a69ce3ea842e.png)

The core api do not really provide this... as far as I can see.
Should we implement the code for the rest api only?

Shouldn't only allow for enrollments status changes?!

2) Should we allow 'custom' status on creation?
Does it make sense create an enrollment for a student/course with a `cancelled` or `expired` status?

**Comment by thomasplevy** [comment] 2019-08-06 16:17
> Should we allow date creation customization?
> 
> The core api do not really provide this... as far as I can see.
> 
> Should we implement the code for the rest api only?

I think we should allow this and I think the core probably should at some point too. Let's move forward with this as specced and we can add something to an interface in the core somewhere as well.

> Should we allow 'custom' status on creation?
> Does it make sense create an enrollment for a student/course with a cancelled or expired status?

I'm not sure if it'll ever make sense to create an enrollment with a cancelled / expired status. However since there's no identifier specific to each enrollment (there's no enrollment id the enrollment "id" is the combined student and post id) the create/update endpoint is the same.

Currently the way enrollments work is everytime the enrollment is updated a new record is created and we determine the current status by querying for the *most recently updated* record.

If we force "enrolled" as the status we'd also prevent unenrollments through this endpoint.

Maybe we should add a default status of enrolled making it so it doesn't have to be passed during a creation.

Thoughts?

**Comment by eri-trabiccolo** [comment] 2019-08-06 16:50
> I'm not sure if it'll ever make sense to create an enrollment with a cancelled / expired status. However since there's no identifier specific to each enrollment (there's no enrollment id the enrollment "id" is the combined student and post id) the create/update endpoint is the same.

Mmm do you mean the route?
The endpoints can actually be different as they can use different methods (update and create share the POST method but update can also be PUT or PATCH - although I agree most likely it'll be POST), and return, as per the specs, two different "success" status...
Am I wrong? I wonder if wp will allow doing that without problems.

> Currently the way enrollments work is everytime the enrollment is updated a new record is created and we determine the current status by querying for the most recently updated record.

Yes.
But as said above I still need a way to differentiate between creation and update because of the success status, no? I think I can do that, e.g. if the `request` method is equal to `WP_REST_Server::CREATABLE` and there's no enrollment for the pair student/course then we're creating.
Do you agree?

> Maybe we should add a default status of enrolled making it so it doesn't have to be passed during a creation.

Maybe yes, it would make sense for the "consumer", although my problem was that I wanted to use `$student->enroll( $product_id, admin_ . get_current_user_id() )` on creation :D

**Comment by eri-trabiccolo** [comment] 2019-08-07 19:01
Man I'm a little bit lost here I have to be honest.
If we allow to create an enrollment with creation date in the future, what would be its status?
I mean none of `expired` `cancelled` `enrolled` would make sense, no?
Additionally: a status update might end up having a "date" which is before the creation date, so we should prevent this too.

Also an `enroll` triggers actions notifications react to...

**Comment by thomasplevy** [comment] 2019-08-07 19:45
> Mmm do you mean the route?
> The endpoints can actually be different as they can use different methods (update and create share the POST method but update can also be PUT or PATCH - although I agree most likely it'll be POST), and return, as per the specs, two different "success" status...
> Am I wrong? I wonder if wp will allow doing that without problems.

Sure we can switch it to `POST` to create and `PATCH` to update. 

Instead of using `WP_REST_Server::CREATABLE` just use `POST` and `PATCH` respectively on the route's methods.

> Yes.
> But as said above I still need a way to differentiate between creation and update because of the success status, no? I think I can do that, e.g. if the request method is equal to WP_REST_Server::CREATABLE and there's no enrollment for the pair student/course then we're creating.
> Do you agree?

Regardless of the request method you'll still need to check if an enrollment record already exists. 

You can use [`LLMS_Student::get_enrollment_status( $post_id )`](https://developer.lifterlms.com/reference/classes/llms_student/get_enrollment_status/).

If we keep it with just `POST` for create/update, you'll need to check to see which return to provide.

If we switch to `POST` or `PATCH` then you'll need to check in order to preform validation. EG: if we want `POST` to be ONLY CREATIONs we'll want to return an error when it already exists and tell them to `PATCH` instead and if they `PATCH` a resource that doesn't exist we need to give them a 404 to note that the enrollment doesn't yet exist.

If we keep it as simply `POST` (call it an "upsert") then the consumer never needs to worry about whether or not the enrollment already exists.

> Maybe yes, it would make sense for the "consumer", although my problem was that I wanted to use $student->enroll( $product_id, admin_ . get_current_user_id() ) on creation 🗡 

Now I'm wondering if the issue is really that we don't have a general management class for enrollment CRUD functions. 

Perhaps most of the enrollment functions which deal with database reads and writes in the `LLMS_Student` class need to be moved into a new class called something like `LLMS_Enrollments` which would have create, read, update, delete methods. Maybe that's too much refactoring to do right now. 

I simply do not have a good solution for this... It all seems like a workaround for not having a well-defined "enrollments" table where we can just update data to reflect the resource...

So if we just switch it to a `POST` for create and a `PATCH` for update and then make it so that there's not post data on request body of a creation -- eg it always creates it NOW with a status of `enrolled` (eg: you cannot create an enrollment in the past or the future) and then allow `PATCHING` to update the status and creation date are we good from your perspective?

**Comment by eri-trabiccolo** [comment] 2019-08-08 14:38
> Sure we can switch it to POST to create and PATCH to update.

> Instead of using WP_REST_Server::CREATABLE just use POST and PATCH respectively on the route's methods.

Yeah makes sense.

> Regardless of the request method you'll still need to check if an enrollment record already exists.
> 
> You can use LLMS_Student::get_enrollment_status( $post_id ).

Yes, I would use that method because of the cache thanks. At the moment to actually get an enrollment "object" I use the same custom SQL query I'm using to fetch the enrollments collection, which is not cached.

> If we keep it with just POST for create/update, you'll need to check to see which return to provide.

Yes, also 'ideally' creation and update need different permissions too. To create you should be able to `enroll` while to update you should be able to `unenroll` too as you can set the enrollment status to `cancelled` or `expired`.

> If we switch to POST or PATCH then you'll need to check in order to preform validation. EG: if we want POST to be ONLY CREATIONs we'll want to return an error when it already exists and tell them to PATCH instead and if they PATCH a resource that doesn't exist we need to give them a 404 to note that the enrollment doesn't yet exist.

I think we have to do this, yes.

> If we keep it as simply POST (call it an "upsert") then the consumer never needs to worry about whether or not the enrollment already exists.

I see, but in my opinion, for the permissions matter etc I think it'll be better to really have two different endpoints, hence using POST for creation and PATCH for update, as you suggested.

> Now I'm wondering if the issue is really that we don't have a general management class for enrollment CRUD functions.

Probably, but actually the thing is, and probably is about my limits :), that I don't understand what is an enrollment with status `enrolled` and creation date set to 1 year from now. 
And do not think the core, as of now, would be able to treat this case any different, does it?!

> Perhaps most of the enrollment functions which deal with database reads and writes in the LLMS_Student class need to be moved into a new class called something like LLMS_Enrollments which would have create, read, update, delete methods. Maybe that's too much refactoring to do right now.

Yeah too much refactoring to do right now.

> So if we just switch it to a POST for create and a PATCH for update and then make it so that there's not post data on request body of a creation -- eg it always creates it NOW with a status of enrolled (eg: you cannot create an enrollment in the past or the future) and then allow PATCHING to update the status and creation date are we good from your perspective?

I think we are.
I will then implement an sql query to change the creation date as well.

Thanks!

**Comment by thomasplevy** [comment] 2019-08-09 01:47
I think I've got all this fixed now with the above commit. If I've missed something please reopen and let me know.

**Closed** 2019-08-09 01:47 UTC
